---
abstract: 'Parsing typed expressions'
author:
  - 'Przemyslaw Wesolek <jest@go.art.pl>'
build_requires:
  Test::Exception: 0
  Test::More: 0.81_01
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Typed-Expression
requires:
  Carp: 0
  Parse::RecDescent: 0
resources:
  repository: git://github.com/jest/perl.mod.Data-Typed-Expression.git
version: 0.005
